### ISSUE TITLE
bug: user ratings return non rated rates

### ISSUE THREAD

**Issue by selankon** [emprius/emprius-app-backend#60]
If a rate is on "pending rates list" should not be returned on any submitted rates lists (tool rates, user rates etc...). 

I detected that specifically on the `GET /users/{id}/rates` return a rate when is already pending. 

I know that on #54 I said: 

> The rating, ratingComment, ratedAt and images can be null if the user didn't rate yet.

This refers to the rating is submitted for only one of the users. **If is pending for both should not be returned**.

**Comment by p4u** [comment]
I think it should be fixed now, please test.

**Comment by selankon** [comment]
Is partially fixed, see this example:

- User1 rated user two but user2 did not. 
- You can see the rate on user1 profile but not on the user2

See this test booking where only one of the users rated http://app.emprius.cat/bookings/67dbda9709263be5dcfc3311 . This rating is only show on  "my ratings screen `ratings/history`" and on the "use ratings screen `users/67b0634802c3074628ee23a5/ratings``"  (they use the same endpoint) and on the booking details page. 

But the rating is not shown on:

- Tool ratings screen
- User2 (the one who didn't rate) ratings pages.
